import "./globals.css";


export const metadata = {
  title: "love-day",
  description: "Generated by falokfy",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
